apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: creator-worker
  namespace: frico
  name: creator-worker
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: creator-worker
  template:
    metadata:
      labels:
        app: creator-worker
      name: creator-worker
    spec:
      serviceAccountName: frico
      automountServiceAccountToken: true
      containers:
        - name: creator
          env:
            - name: LOG_LEVEL
              value: WARNING
            - name: REDIS_HOST
              value: redis-master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
          image: ghcr.io/nemcikjan/dizp-eaoda-worker
          imagePullPolicy: IfNotPresent
          args:
            - /app/pod_creator.worker.py
      terminationGracePeriodSeconds: 5
