apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frico
resources:
  - redis
secretGenerator:
  - literals:
      - redis-password=9B42KrXV4j
    name: redis-secret
    options:
      disableNameSuffixHash: true
configMapGenerator:
  - files:
      - fluent-bit.conf
    name: fluentbit-config
