apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frico
resources:
  - redis
  - controller.deployment.yml
  - worker.deployment.yml
  - rbac.yml
  - sa.yml
secretGenerator:
  - literals:
      - redis-password=9B42KrXV4j
    name: redis-secret
    options:
      disableNameSuffixHash: true
configMapGenerator:
  - files:
      - fluent-bit.conf
    name: fluentbit-config
images:
  - name: ghcr.io/nemcikjan/dizp-eaoda-worker
    newTag: v20240203-bfadb08
  - name: ghcr.io/nemcikjan/dizp-eaoda-controller
    newTag: v20240203-bfadb08
