apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frico
resources:
  - redis
  - controller.yml
  - balancer-controller.yml
  # - worker.deployment.yml
  - creator.yml
  - deleter.yml
  - watcher.yml
  - rescheduler.yml
  - cleaner.yml
  - rbac.yml
  - sa.yml
  - ingress.yml
secretGenerator:
  - literals:
      - redis-password=9B42KrXV4j
    name: redis-secret
    options:
      disableNameSuffixHash: true
configMapGenerator:
  - files:
      - fluent-bit.conf
    name: fluentbit-config
images:
  - name: ghcr.io/nemcikjan/dizp-eaoda-worker
    newTag: v20240208-b5489b7
  - name: ghcr.io/nemcikjan/dizp-eaoda-controller
    newTag: v20240208-b5489b7
