apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: watcher-worker
  namespace: frico
  name: watcher-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: watcher-worker
  template:
    metadata:
      labels:
        app: watcher-worker
      name: watcher-worker
    spec:
      serviceAccountName: frico
      containers:
        - name: deleter
          env:
            - name: REDIS_HOST
              value: redis-master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
          image: ghcr.io/nemcikjan/dizp-eaoda-worker
          imagePullPolicy: IfNotPresent
          args:
            - /app/pod_watcher.worker.py
      terminationGracePeriodSeconds: 5
