apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: redis
    repo: https://charts.bitnami.com/bitnami
    releaseName: redis
    version: ^18.11
    valuesInline:
      architecture: standalone
      image:
        tag: 6.2.14-debian-11-r6
      # global:
      #   storageClass: microk8s-hostpath
      auth:
        existingSecret: redis-secret
      master:
        # nodeSelector:
        #   name: odin
        disableCommands:
          - FLUSHALL
